url: "https://www.klara-theme.netlify.app"
title: LYNN
description: >-
    Description of this page.
mail: "yourmailhere@protonmail.com"

# Choose color-theme
color-theme: color #bw, color
background-image: "" # Path to background-image

# Add Plugins
plugins:
  - webrick
  - jekyll-sitemap
  - jekyll-gzip

# Clean Code Output
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
sass:
  style: compressed

# Exclude from Build
exclude:
  - .jekyll-cache

# Define Collections
permalink: pretty
