url: "https://www.klara-theme.netlify.app"
title: LYNN
show_description_on_card: True  # Your name/brand
description: >-
    Lynn is a Cologne-based producer crafting dark ambient electro and experimental soundscapes.
mail_text: "Email me"   # Link text for you email address
mail: "mailto:your@email.com"  # Your email address
color-theme: color      # Choose "color", "bw" or create your own theme
background-image: ""    # Optional background image path

# Add Plugins
plugins:
  - webrick
  - jekyll-sitemap
  - jekyll-gzip

# Clean Code Output
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
sass:
  style: compressed

# Exclude from Build
exclude:
  - .jekyll-cache

# Define Collections
permalink: pretty
